module.exports = {
    "up": "CREATE TABLE IF NOT EXISTS `groups` ("
        + " `guid` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,"
        + " `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,"
        + " `type` enum('public','password','private') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'private',"
        + " `password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,"
        + " `icon` varchar(3000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,"
        + " `description` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,"
        + " `metadata` json DEFAULT NULL,"
        + " `owner` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT 'app_system',"
        + " `membersCount` int NOT NULL DEFAULT '0',"
        + " `createdAt` int NOT NULL,"
        + " `updatedBy` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,"
        + " `updatedAt` int DEFAULT NULL,"
        + " PRIMARY KEY (`guid`),"
        + " KEY `groups_name_index` (`name`),"
        + " KEY `groups_type_index` (`type`),"
        + " KEY `groups_owner_index` (`owner`),"
        + " KEY `groups_createdat_index` (`createdAt`),"
        + " KEY `groups_updatedat_index` (`updatedAt`),"
        + " KEY `groups_updatedby_index` (`updatedBy`),"
        + " CONSTRAINT `groups_owner_foreign` FOREIGN KEY (`owner`) REFERENCES `users` (`uid`) ON DELETE SET NULL" + " ON UPDATE CASCADE"
        + " ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
    "down": "DROP TABLE `groups`;"
}