module.exports = {
    "up": "CREATE TABLE IF NOT EXISTS `auth_tokens` ("
        + " `authToken` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,"
        + " `uid` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,"
        + " `deviceId` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,"
        + " `apiKey` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,"
        + " `platform` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,"
        + " `userAgent` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,"
        + " `appInfo` json DEFAULT NULL,"
        + " `createdAt` int NOT NULL,"
        + " `updatedAt` int unsigned DEFAULT NULL,"
        + " `deletedAt` int unsigned DEFAULT NULL,"
        + " PRIMARY KEY (`authToken`),"
        + " KEY `auth_tokens_uid_foreign` (`uid`),"
        + " KEY `auth_tokens_apikey_index` (`apiKey`),"
        + " KEY `auth_tokens_platform_index` (`platform`),"
        + " KEY `auth_tokens_useragent_index` (`userAgent`),"
        + " KEY `auth_tokens_createdat_index` (`createdAt`),"
        + " KEY `auth_tokens_deviceid_index` (`deviceId`),"
        + " KEY `auth_tokens_updatedat_index` (`updatedAt`),"
        + " KEY `auth_tokens_deletedat_index` (`deletedAt`),"
        + " KEY `auth_tokens_deviceid_uid_deletedat_index` (`deviceId`,`uid`,`deletedAt`),"
        + " CONSTRAINT `auth_tokens_uid_foreign` FOREIGN KEY (`uid`) REFERENCES `users` (`uid`) ON DELETE CASCADE"
        + " ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;",
    "down": "DROP TABLE `auth_tokens`;"
}